// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMRt1nxxWh6XkJ39ERy6AqBZn5B7LE2mM',
    appId: '1:568939278305:web:04b3bba2526409edeaeca0',
    messagingSenderId: '568939278305',
    projectId: 'netzme-af178',
    authDomain: 'netzme-af178.firebaseapp.com',
    storageBucket: 'netzme-af178.appspot.com',
    measurementId: 'G-SCCGZ5LTN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQYkNu4N1WtUsvGax-jXdsg3dBEXmTMHA',
    appId: '1:568939278305:android:74253933207b6912eaeca0',
    messagingSenderId: '568939278305',
    projectId: 'netzme-af178',
    storageBucket: 'netzme-af178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh-EdlOoN8RhfY2m9NO6xZDEGpFVucRd8',
    appId: '1:568939278305:ios:264f9472c4ba6566eaeca0',
    messagingSenderId: '568939278305',
    projectId: 'netzme-af178',
    storageBucket: 'netzme-af178.appspot.com',
    iosBundleId: 'com.example.netzme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh-EdlOoN8RhfY2m9NO6xZDEGpFVucRd8',
    appId: '1:568939278305:ios:06c62fc9477fc843eaeca0',
    messagingSenderId: '568939278305',
    projectId: 'netzme-af178',
    storageBucket: 'netzme-af178.appspot.com',
    iosBundleId: 'com.example.netzme.RunnerTests',
  );
}
